[build]
  command = "npm install && pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "."

[[plugins]]
package = "@netlify/plugin-python"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200 