[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  directory = "api"
  node_bundler = "esbuild"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200 