[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200 